### ISSUE TITLE
Bayesian requires pyro which can't be installed

### ISSUE THREAD

**Issue by amueller** [Ji-Zhang/datacleanbot#1]
I'm trying to import dataclean, but it looks like the bayesian subpackage requires pyro. ``pyro`` doesn't seem to be in ``requirements.txt`` and ``pip install pyro`` fails (seems like it might be a python2 package?)

**Comment by amueller** [comment]
looks like the required package might be ``pyro-ppl``?

**Comment by amueller** [comment]
rpy2 is also a dependency that's not documented

**Comment by Ji-Zhang** [comment]
> looks like the required package might be `pyro-ppl`?

Yes, just updated that. Thanks!

**Comment by Ji-Zhang** [comment]
> rpy2 is also a dependency that's not documented

Thanks. Updated already. And now the package has been published such that it can be installed via pip install datacleanbot.

**Comment by amueller** [comment]
that's great, thanks! The dependencies are still a bit heavy but I guess that's hard to change (theano, torch and tensorflow are all required).
