### ISSUE TITLE
Paper references

### ISSUE THREAD

**Issue by kellieotto** [Ji-Zhang/datacleanbot#6]
This issue is part of your [JOSS review](https://github.com/openjournals/joss-reviews/issues/1608).

The second reference in your paper bibliography is formatted in a strange way (check the compiled PDF). Please add DOIs for the 2nd-4th references (if they have a DOI).

**Comment by Ji-Zhang** [comment]
Thanks. The reference has already been fixed.

**Comment by kellieotto** [comment]
Looks good
